version: 1.0.{build}
image: Visual Studio 2017
environment:
  APPVEYOR: 1
install:
  - docker version
  - node --version
  - cmd: >-
      choco install selenium-chrome-driver --version 2.37
build_script:
  - cmd: npm install
  - docker images
  - docker ps
  - docker swarm init --advertise-addr 10.0.75.1
  - docker stack deploy --compose-file C:\projects\terra-core\node_modules\terra-toolkit\config\docker\local-docker-compose.yml wdio
test_script:
    - cmd: npm run wdio
