version: 1.0.{build}
image: Visual Studio 2017
environment:
  APPVEYOR: 1
install:
- docker version
- cmd: >-
    choco install selenium-chrome-driver --version 2.37
build_script:
- cmd: npm install
test_script:
- cmd: npm run wdio
